spring.application.name=microservice-image

server.port=0

# Change in the future
# MongoDB
spring.mongodb.host=127.0.0.1
spring.mongodb.port=27017
spring.mongodb.authentication-database=${DB_AUTH}
spring.mongodb.username=${DB_USERNAME}
spring.mongodb.password=${DB_PASSWORD}
spring.mongodb.protocol=mongodb
spring.mongodb.replica-set-name=rs0

# Redis - distb. locks
spring.data.redis.database=1
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379

# MinIO
minio.hostname=127.0.0.1
minio.port=9000
minio.secure=false
minio.access-key=minioadmin
minio.secret-key=minioadmin

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# app specific custom properties
rabbitmq.bind.key.image=queue.image.removed
rabbitmq.exchange.image=ImagesRemoved

rabbitmq.bind.key.user=queue.user.removed
rabbitmq.exchange.user=UsersRemoved

rabbitmq.queue.image=ImagesMicro


app.user.max.images=20
app.image.max.sizeInKB=300
