spring.application.name=microservice-image


# app specific custom properties
app.user.max.images=20

#   root image persistence dir (obviamente temporal el dir elegido)
app.persistence.filesystem.root=${project.basedir}/main/java/resources/static