# Mongodb
logging.level.org.springframework.data.mongodb.core.MongoTemplate: DEBUG
spring.mongodb:
  database: "dndservice_db_test"
  replica-set-name:
# MinIO
minio.bucket.name: "test"
# RabbitMQ
spring.rabbitmq.virtual-host: "vTest"
# Eureka
eureka.client.enabled: false
# App specific
app:
  sampleImagePath: "./src/main/resources/static/sampleImage.png"
  sampleOverSizedImagePath: "./src/main/resources/static/sampleImageOverSized.png"
  sampleFilePath: "./src/main/resources/static/sampleFile.txt"