spring.application.name=microservice-characterSheet

server.port=0

# Change in the future
spring.mongodb.host=127.0.0.1
spring.mongodb.port=27017
spring.mongodb.authentication-database=${DB_AUTH}
spring.mongodb.username=${DB_USERNAME}
spring.mongodb.password=${DB_PASSWORD}
spring.mongodb.protocol=mongodb