spring.application.name=api-gateway

eureka.instance.instance-id=${spring.application.name}:${random.uuid}

spring.cloud.gateway.server.webmvc.routes[0].id=microservice-user
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://MICROSERVICE-USER
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/users/**

spring.cloud.gateway.server.webmvc.routes[1].id=microservice-characterSheet
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://MICROSERVICE-CHARACTERSHEET
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/charSheets/**

# App config
rateLimit.bucket.capacity=1
rateLimit.bucket.periodInMinutes=1