spring.application.name=api-gateway
# Eureka config
eureka.instance.instance-id=${spring.application.name}:${random.uuid}

# Rate limiter
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
spring.data.redis.database=0

# Routes
#spring.cloud.gateway.server.webmvc.routes[0].id=microservice-user
#spring.cloud.gateway.server.webmvc.routes[0].uri=lb://MICROSERVICE-USER
#spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/users/**

#spring.cloud.gateway.server.webmvc.routes[1].id=microservice-characterSheet
#spring.cloud.gateway.server.webmvc.routes[1].uri=lb://MICROSERVICE-CHARACTERSHEET
#spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/charSheets/**
#
#spring.cloud.gateway.server.webmvc.routes[2].id=microservice-lobby-rs
#spring.cloud.gateway.server.webmvc.routes[2].uri=lb://MICROSERVICE-LOBBY
#spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/lobbies/**
#
#spring.cloud.gateway.server.webmvc.routes[3].id=microservice-lobby-sockJs
#spring.cloud.gateway.server.webmvc.routes[3].uri=lb://MICROSERVICE-LOBBY
#spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/v1/lobbies/**
#
#spring.cloud.gateway.server.webmvc.routes[4].id=microservice-lobby-ws
#spring.cloud.gateway.server.webmvc.routes[4].uri=lb://MICROSERVICE-LOBBY
#spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/v1/lobbies/**
#
#spring.cloud.gateway.server.webmvc.routes[5].id=microservice-image
#spring.cloud.gateway.server.webmvc.routes[5].uri=lb://MICROSERVICE-IMAGE
#spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/v1/images/**

# App config
rateLimit.bucket.capacity=50
rateLimit.bucket.refillInSeconds=1


