# Mongodb config
spring.mongodb.database: "dndservice_db_board"
# RabbitMQ config
rabbitmq:
  virtual-host:
    ws: "vLobbiesStomp"
    mb: "vMicroservicesMQ"
# Eureka config
eureka.instance.instance-id: "${spring.application.name}:${random.uuid}"