spring.application.name=microservice-lobby

server.port=0

# Change in the future
spring.mongodb.host=127.0.0.1
spring.mongodb.port=27017
spring.mongodb.authentication-database=${DB_AUTH}
spring.mongodb.username=${DB_USERNAME}
spring.mongodb.password=${DB_PASSWORD}
spring.mongodb.protocol=mongodb
spring.mongodb.replica-set-name=rs0

spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
spring.data.redis.database=0

# change in the future
spring.rabbitmq.host=127.0.0.1

rabbitmq.port.ws=61613
rabbitmq.port.mb=5672

spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

rabbitmq.bind.key.image=queue.image.removed
rabbitmq.exchange.image=ImagesRemoved

rabbitmq.bind.key.user=queue.user.removed
rabbitmq.exchange.user=UsersRemoved

rabbitmq.queue.lobby.user=LobbiesMicro.user
rabbitmq.queue.lobby.image=LobbiesMicro.image

# app specific properties
app.user.max.boards=3
app.lobby.board.max.pieces=30
app.lobby.max.users=10