logging.level.org.springframework.data:
  transaction: DEBUG
  mongodb.core.MongoTemplate: DEBUG
  redis.core.RedisTemplate: DEBUG
spring.mongodb.database: "dndservice_db_test"

eureka.client.enabled: false
