logging.level.org.springframework:
  amqp:
    rabbit:
      AsyncRabbitTemplate: DEBUG
      core.RabbitTemplate: DEBUG
    core.AmqpTemplate: DEBUG
  data:
    transaction: DEBUG
    mongodb.core.MongoTemplate: DEBUG
    redis.core.RedisTemplate: DEBUG
spring.mongodb.database: "dndservice_db_test"
# RabbitMQ config
rabbitmq:
  virtual-host:
    ws: "vTest"
    mb: "vTest"
# Eureka config
eureka.client.enabled: false
