# Mongodb config
spring.mongodb.database: "dndservice_db_board"
# RabbitMQ config
spring.rabbitmq.virtual-host: "vLobbiesStomp"
# Eureka config
eureka.instance.instance-id: "${spring.application.name}:${random.uuid}"