spring.application.name=microservice-user

server.port=8080

spring.mongodb.host=127.0.0.1
spring.mongodb.port=27017
spring.mongodb.authentication-database=${DB_AUTH}
spring.mongodb.username=${DB_USERNAME}
spring.mongodb.password=${DB_PASSWORD}
spring.mongodb.protocol=mongodb

admin.pwd = $2a$12$NBFIUzzLsYDCWIn1IWouvefj3/b21SgGBGlkcQYcDBii7qzQfB3s6
admin.email = random@gmail.com

jwt.secret=5Sa8Gi3nof023iN09h8302nmaPsnBD92
jwt.expiration=8640000