spring.application.name=microservice-user

server.port=0

# Eureka config
eureka.instance.instance-id=${spring.application.name}:${random.uuid}

# Change in the future
spring.mongodb.host=127.0.0.1
spring.mongodb.port=27017
spring.mongodb.authentication-database=${DB_AUTH}
spring.mongodb.username=${DB_USERNAME}
spring.mongodb.password=${DB_PASSWORD}
spring.mongodb.protocol=mongodb

# Change in the future
admin.cyptedPwd = $2a$12$CF6z0iLqRvtCfFD2ytOwCeGhbGhBdN4Vjy2Ndt52aXUYByRdjDrES
admin.pwd = seC8et$zasdada
admin.email = random@gmail.com
# Change in the future
jwt.secret=NVNhOEdpM25vZjAyM2lOMDloODMwMm5tYVBzbkJEOTI=
jwt.expiration=8640000