spring.application.name=microservice-characterSheet

server.port=0

# Redis
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
spring.data.redis.database=0

# Change in the future
spring.mongodb.host=127.0.0.1
spring.mongodb.port=27017
spring.mongodb.authentication-database=${DB_AUTH}
spring.mongodb.username=${DB_USERNAME}
spring.mongodb.password=${DB_PASSWORD}
spring.mongodb.protocol=mongodb
spring.mongodb.replica-set-name=rs0

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# app specific custom properties
rabbitmq.bind.key.image=queue.image.removed
rabbitmq.exchange.image=ImagesRemoved

rabbitmq.bind.key.user=queue.user.removed
rabbitmq.exchange.user=UsersRemoved

rabbitmq.queue.charSheet=CharSheetsMicro

app.user.max.characterSheets=10
